# CodeRabbit Configuration
# This file configures the CodeRabbit AI code review agent

# Patterns to be excluded during code review
exclude_patterns:
  - "**/*.pb.go"              # Protocol buffer generated files
  - "**/*.pb.gw.go"           # gRPC gateway generated files
  - "vendor/**"               # Vendored dependencies
  - "node_modules/**"         # Node modules
  - "**/*.min.js"             # Minified JavaScript
  - "**/*.min.css"            # Minified CSS
  - ".git/**"                 # Git directory
  - "bin/**"                  # Built binaries

# Patterns to be included for code review
include_patterns:
  - "**/*.go"                 # Go source files
  - "**/*.proto"              # Protocol buffer definitions
  - "**/*.yaml"               # YAML configuration files
  - "**/*.yml"                # YAML configuration files
  - "**/*.md"                 # Markdown documentation
  - "go.mod"                  # Go module file
  - "go.sum"                  # Go sum file

# Code review rules and preferences
rules:
  # Code quality checks
  - id: "code-quality"
    enabled: true
    description: "Check for code quality issues"
    
  # Security checks
  - id: "security"
    enabled: true
    description: "Check for security vulnerabilities and issues"
    severity: "high"
    
  # Performance checks
  - id: "performance"
    enabled: true
    description: "Check for performance issues"
    
  # Go-specific checks
  - id: "go-best-practices"
    enabled: true
    description: "Check Go best practices"
    rules:
      - error_handling: "Ensure errors are properly handled"
      - defer_usage: "Check for proper defer usage"
      - goroutine_leaks: "Check for goroutine leaks"
      - nil_checks: "Check for nil pointer dereferences"

# Review settings
review_settings:
  # Automatically review pull requests
  auto_review: true
  
  # Review files changed in the PR
  review_changed_files: true
  
  # Review file comments
  review_comments: true
  
  # Review commits
  review_commits: true
  
  # Require human review
  require_human_review: false
  
  # Post review summary
  post_summary: true
  
  # Maximum files to review per PR
  max_files: 100
  
  # Minimum number of changed lines to trigger review
  min_changed_lines: 1

# Language-specific configurations
languages:
  go:
    enabled: true
    # Check for common Go issues
    checks:
      - unused_variables
      - unused_imports
      - missing_error_handling
      - race_conditions
      - memory_leaks
      - concurrent_access
  
  proto:
    enabled: true
    checks:
      - syntax_errors
      - deprecated_features

# Focus areas for this project
focus_areas:
  - graceful_shutdown      # Monitor graceful shutdown implementation
  - certificate_management # Monitor certificate loading and management
  - tls_security          # Monitor TLS security configurations
  - concurrency           # Monitor goroutines and channel usage
  - error_handling        # Monitor error handling patterns

# Severity levels
severity_levels:
  critical:
    - "security vulnerability"
    - "data loss"
    - "memory safety"
  high:
    - "race condition"
    - "goroutine leak"
    - "improper error handling"
  medium:
    - "code quality"
    - "performance degradation"
    - "unused code"
  low:
    - "style issues"
    - "documentation"
    - "minor improvements"

# Notification settings
notifications:
  # Post comments on PR
  post_pr_comments: true
  
  # Comment on specific lines
  post_line_comments: true
  
  # Tag reviewers
  mention_reviewers: false

# Integration settings
integration:
  github:
    enabled: true
    # Check PR title and description
    check_pr_description: true
    # Require PR description
    require_description: false
