linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - goimports
    - goconst
    - unconvert
    - gofmt
    - gofumpt
    - gosec
    - misspell
    - revive

linters-settings:
  revive:
    min-confidence: 0.8

run:
  timeout: 5m
  tests: true
